#!/bin/sh

echo "------------------------------------------------------------"
echo "------------------------------------------------------------"
if [ "$(find /var/lib/docker |  wc -l)" -gt 1 ]
then
  echo "-- Rehydrating /var/lib/docker --"
  cp -r /_docker/ /var/lib/docker/
else
  echo "-- No need to rehydrate /var/lib/docker --"
fi
echo "------------------------------------------------------------"
echo "------------------------------------------------------------"
